name: Docker CI/CD

on:
  push:
    branches:
      - main  # Se ejecuta cuando subes cambios a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Iniciar Docker Build
        run: docker build -t mi-imagen-docker .

      - name: Subir imagen a Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

